version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dronedb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'